[package]
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "bios-spi-stats"
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "bios_spi_stats"
path = "src/lib.rs"

[features]
default = ["spi-pg"]
spi-pg = ["tardis/reldb-postgres"]

[dependencies]
bios-basic = {version = "0.2.0", path = "../../basic", features = ["default"]}
bios-sdk-invoke = {version = "0.2.0", path = "../../../frontend/sdks/invoke", features = [
  "event",
  "spi_log",
  "schedule",
  "spi_stats",
], default-features = false}
itertools.workspace = true
lazy_static.workspace = true
serde.workspace = true
serde_json = {workspace = true, features = ["preserve_order"]}
strum = {workspace = true, features = ["derive"]}
tardis = {workspace = true, features = ["reldb-postgres", "web-server"]}

[dev-dependencies]
bios-basic = {version = "0.2.0", path = "../../basic", features = [
  "default",
  "test",
]}
tardis = {workspace = true, features = ["test"]}
