[package]
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "bios-spi-plugin"
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "bios_spi_plugin"
path = "src/lib.rs"

[features]
default = ["spi-pg"]
spi-pg = ["tardis/reldb-postgres"]
with-mq = ["tardis/mq"]
[dependencies]
async-trait.workspace = true
bios-basic = {version = "0.2.0", path = "../../basic", features = ["default"]}
bios-sdk-invoke = {version = "0.2.0", path = "../../../frontend/sdks/invoke", features = ["default"]}
percent-encoding = "2"
serde.workspace = true
strum = {workspace = true, features = ["derive"]}
tardis = {workspace = true, features = ["reldb-postgres", "web-server"]}
[dev-dependencies]
bios-basic = {version = "0.2.0", path = "../../basic", features = ["default", "test"]}
bios-sdk-invoke = {version = "0.2.0", path = "../../../frontend/sdks/invoke", features = ["default"]}
tardis = {workspace = true, features = ["test", "ws-client"]}

[[test]]
name = "test_plugin"
required-features = ["default", "with-mq"]
